version: '3'
services:
  react:
    container_name: ti_react01
    restart: always
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
    - "8001:8001"
    expose:
      - "8001"
    volumes:
    - .:/app
    - ti_modules:/app/node_modules
    command: sh -c "yarn install && yarn start"

volumes:
  ti_modules:
