version: '3'
services:
  node:
    container_name: ti_node01
    restart: always
    build:
      context: .
      dockerfile: ./Backend_Dockerfile
    ports:
    - "8100:80"
    expose:
    - "80"
    volumes:
    - ./server:/app
    - s_modules:/app/node_modules
    links:
    - mysql

  mysql:
    restart: always
    image: mysql:5.7.13
    container_name: ti_mysql01
    env_file:
      - ./server/.env
    volumes:
      - ti_mysql:/var/lib/mysql
    expose:
      - "3306"
    ports:
      - "33061:3306"

  react:
    container_name: ti_react01
    build:
      context: .
      dockerfile: ./Frontend_Dockerfile
    ports:
    - "8101:8101"
    expose:
      - "8101"
    volumes:
    - .:/app
    - ./client/node_modules:/app/client/node_modules
    - c_modules:/app/client/node_modules
    command: sh -c "yarn && yarn start"
    links:
    - node

volumes:
  c_modules:
  s_modules:
  ti_mysql:
