# Need relative to app Root directory. use '--project-directory .' in command
# Example: docker-compose -f scripts/docker/docker-compose.backend.yml --project-directory .

version: '3'
services:
  backend: 
    container_name: ti_backend01
    restart: always
    image: ti-base-node
    ports:
    - "8100:80"
    expose:
    - "80"
    volumes:
    - ./:/app
    - node_modules:/app/node_modules
    links:
    - mysql
    command: "yarn be nodemon"
    tty: true

  mysql:
    restart: always
    image: mysql:5.7.13
    container_name: ti_mysql01
    env_file:
      - ./parts/backend/.env
    volumes:
      - mysql:/var/lib/mysql
    expose:
      - "3306"
    ports:
      - "33601:3306"

volumes: 
  mysql:
  node_modules:
