# Need relative to app Root directory. use '--project-directory .' in command
# Example: docker-compose -f scripts/docker/docker-compose.backend.yml --project-directory .

version: '3'
services:
  watch: 
    container_name: ti_watch01
    restart: always
    image: ti-base-node
    volumes:
    - ./:/app
    command: "yarn be tsc"
    tty: true
    environment: 
    - TERM=xterm-256color`
